[package]
name = "concept_db"
version = "0.1.0"
edition = "2024"
description = "A key-value DB for converting structs into a DB of assorted json files"
license = "MIT"
[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
warp = { version = "0.4.2", features = ["server"] }
